### ISSUE TITLE
MBTI issue

### ISSUE THREAD

**Issue by tobit1024** [LSH9132/Japanese-Character-MBTI-Test#1]
저 엠비티아이 비정상이라는데 이거 문제 있는건가요..?
![image](https://github.com/user-attachments/assets/c5ef0b36-4611-4ee6-9fe1-ca199deec269)

**Comment by LSH9132** [comment]
네

**Comment by LSH9132** [comment]
> 저 엠비티아이 비정상이라는데 이거 문제 있는건가요..? ![image](https://private-user-images.githubusercontent.com/61526826/370589215-c5ef0b36-4611-4ee6-9fe1-ca199deec269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDY0MDAsIm5iZiI6MTcyNzI0NjEwMCwicGF0aCI6Ii82MTUyNjgyNi8zNzA1ODkyMTUtYzVlZjBiMzYtNDYxMS00ZWU2LTlmZTEtY2ExOTlkZWVjMjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA2MzUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZjhlNmU3Y2U3ODk2Mjc2NTBlYWI3MjY3ODRkZWE3YzM2Y2IyMjZmYzY4NDEzMzZlZmZkOGZjMzg2YWEzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j_HKG7c9A-QVRnbF-0WpEp2vg7ZNcbeG5FkCFd15SLk)

네
